name: CI/CD Pipeline - Practica 3

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test step
        run: echo "test"

      - name: Run health-check test
        run: |
          pip install flask
          python app/app.py &
          sleep 5
          curl -f http://localhost:8000/status

  build:
    name: Build stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build step
        run: echo "build"

  deploy:
    name: Deploy stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        run: echo "deploy"
